# Generated by Django 3.2.9 on 2022-04-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='mac_address',
            field=models.CharField(default='mac', max_length=30),
            preserve_default=False,
        ),
    ]
